version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: ai-pairing-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=ai-pairing

  # Backend API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-pairing-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/ai-pairing
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai-pairing-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  # AI Model service (using Python)
  ai-model:
    build:
      context: ./ai-server
      dockerfile: Dockerfile.model
    container_name: ai-pairing-model
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./ai-server:/app
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Docker Volumes
volumes:
  mongodb_data:
    driver: local
